server:
  port: 9696

spring:
  redis:
    # Redis 数据库索引
    database: 0
    #     Redis 服务器地址
    host: 127.0.0.1
#    host: 192.168.35.128
    #     Redis 服务器端口
    port: 6379
    # Redis 服务器连接密码
    #password: 123456
    # 连接池设置
    pool:
      # 最大连接数量 -1无限制
      max-active: 8
      # 最大阻塞等待时间 -1无限制
      max-wait: -1
      # 最大空闲连接
      max-idle: 8
      # 最小空闲连接
      min-idle: 0
    # 连接超时时间
    timeout: 1000

lz:
  security:
    # [非必需] 是否打印日志信息(默认true)
    console-log-print: true
    # Token相关配置
    token-config:
      # [非必需] Token存放标识(默认Authorization)
      name: FILTER_TOKEN
      ## Token 前缀
      prefix :
      # [非必需] 类型(默认UUID)(UUID、JWT)(可通过重写IAccessTokenHandler.class来实现自定义token类型,重写后此项将无效)
      #type: JWT
      # [非必需] 过期时间(秒)(默认3600秒)
      timeout: 3600
    # 加解密相关配置
    encrypt-config:
      # [非必需] 是否加解密(默认false)
      encrypt: true
      cipher-save-key: data
      encrypt-handler-class: cn.lz.security.defaults.AESDataEncoder
      params:
        key: 1234567812345678
        iv: 1234567812345678
    filter-config:
      exclude-url-list:
        - /include/decrypt
        - /favicon.ico
        - /webjars/**
        - /doc.html
        - /swagger-resources
        - /v2/api-docs
        - /v2/api-docs-ext
        - /exclude/**
      include-url-list:
        - /include/**
